---
driver:
  provision: true

provisioner:
  custom_options: '--show_diff'
  hiera_config_path: ./hiera.yaml
  hiera_data_path: hieradata
  hiera_data_remote_path: hieradata
  hiera_deep_merge: true
  manifests_path: examples
  modules_path: modules
  name: puppet_apply
  puppet_debug: false
  puppet_verbose: true
  puppet_yum_repo: https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm
  require_chef_for_busser: false
  require_chef_omnibus: false
  require_puppet_collections: false
  require_puppet_repo: true
  sudo: true
  username: vagrant
  wait_for_retry: 10

transport:
  name: rsync
  compression: true

busser:
  ruby_bindir: /usr/bin

platforms:
  - name: centos-73-vagrant
    driver_plugin: vagrant
    driver_config:
      box: bento/centos-7.3
      linked_clone: true
      vagrantfiles:
        - install-basics.rb
  - name: centos-72-vagrant
    driver_plugin: vagrant
    driver_config:
      box: bento/centos-7.2
      linked_clone: true
      vagrantfiles:
        - install-basics.rb

suites:
  - name: base
    provisioner:
      custom_pre_apply_command: |
        echo "Preparing the environment ..."
        false
      manifest: basic.pp
    includes:
      - centos-73-vagrant
      - centos-72-vagrant

  - name: advanced
    provisioner:
      custom_pre_apply_command: |
        echo "Preparing the environment ..."
      manifest: advanced.pp
    includes:
      - centos-73-vagrant
      - centos-72-vagrant
