# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

# implicitely inherits from {default.yml, disabled.yml, enabled.yml}
# from $HOME/.gem/ruby/2.3.0/gems/rubocop-0.49.1/config/

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'modules/**/*'

Layout/CaseIndentation:
  EnforcedStyle: case
  SupportedStyles:
    - case
    - end
  IndentOneStep: true
  IndentationWidth: ~

Layout/CommentIndentation:
  Exclude:
    - Puppetfile

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
  SupportedStyles:
    - aligned
    - indented
    - indented_relative_to_receiver
  IndentationWidth: ~

Style/CommandLiteral:
  EnforcedStyle: percent_x
  SupportedStyles:
    - backticks
    - percent_x
    - mixed
  AllowInnerBackticks: false

Style/FormatStringToken:
  EnforcedStyle: template
  SupportedStyles:
    - annotated
    - template

Style/HashSyntax:
  Exclude:
    - Puppetfile

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
